CREATE TABLE IF NOT EXISTS user(
    id BIGINT AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    username VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(50)  NOT NULL,
    code VARCHAR(50)  NOT NULL,
    birth DATE NOT NULL,
    register DATETIME NOT NULL,
    status SMALLINT(1) NOT NULL DEFAULT(0),
    type SMALLINT(1) NOT NULL DEFAULT(0),
    PRIMARY KEY(id)
);